name: zilch_workout
description: A mobile smart trainer app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_bloc: ^7.0.1
  amplify_flutter: ^0.2.2
  amplify_auth_cognito: ^0.2.2
  amplify_datastore: ^0.2.2
  amplify_api: ^0.2.2
  amplify_storage_s3: ^0.2.2
  path_provider: ^2.0.2
  shared_preferences: ^2.0.5
  flutter_calendar_carousel: ^2.0.1
  messagepack: ^0.2.1
  keyboard_actions: ^3.4.0
  flutter_reorderable_list: ^1.0.0
  flutter_blue: ^0.8.0
  #bluetooth require permission, plist, manifest
  equations: ^2.1.1
  intl: ^0.17.0
  audioplayers: ^0.19.0
  #audioplayers require android sdk >=23
  wakelock: ^0.5.2
  flutter_local_notifications: ^6.0.0
  flutter_native_timezone: ^1.1.0
  google_mobile_ads: ^0.13.0
  #info.plist, androidmanifest(todo)
  uuid: ^3.0.4
  url_launcher: ^6.0.9
  flutter_html: ^2.1.1
  rate_my_app: ^1.1.1
  share_plus: ^2.1.4
  strava_flutter:
    git:
      url: git://github.com/BirdyF/strava_flutter.git


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/images/appIcon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sounds/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
